[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'params_first'
quote_style = 'single'
number_underscore = 'thousands'
wrap_comments = false

[profile.docs]
title = 'Open Dollar Docs'
src = 'src/'               # root_path variable in build-docs.sh

[profile.default]
auto_detect_solc = true
src = 'src'
test = 'test'
out = 'out'
libs = ['lib']
fuzz_runs = 1000
optimizer_runs = 10_000
block_timestamp = 1675855961
# fs_permissions = [{ access = "write", path = "./test/simulations" }]
fs_permissions = [{ access = "read-write", path = "./" }]
fuzz_max_test_rejects = 10000000

[profile.governance]
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.optimized]
via_ir = true
out = 'out-via-ir'
fuzz_runs = 5000

[profile.test]
via_ir = false
out = 'out-via-ir'
fuzz_runs = 5000
src = 'test'
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
mainnet = "${ARB_MAINNET_RPC}"
sepolia = "${ARB_SEPOLIA_RPC}"
