name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: PR Continuous Integration
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install
        shell: bash
        run: yarn install

      - name: Build
        shell: bash
        run: yarn build
