name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: PR Continuous Integration
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install
        shell: bash
        run: yarn install

      - name: Build
        shell: bash
        run: yarn build

      - name: Run tests
        run: forge test -vvv
