name: CI - Pull Request

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    name: PR Continuous Integration
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Install
        shell: bash
        run: yarn

      - name: Build
        shell: bash
        run: yarn build
